name: ci

on: push

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform_version: [13]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
          # more setup-terraform configuration. See https://github.com/hashicorp/setup-terraform#usage
          #
      - name: run terraform init
        run: |
            cd test/fixture/terraform_13/aws_autoscaling_group/input && terraform init

      - uses: env0/terratag-action@v1
        with:
          cli_args: -tags={\"env0_environment_id\":\"40907eff-cf7c-419a-8694-e1c6bf1d1168\",\"env0_project_id\":\"43fd4ff1-8d37-4d9d-ac97-295bd850bf94\"} -dir=test/fixture/terraform_13/aws_autoscaling_group/input 
          # more terratag configuration. See https://github.com/env0/terratag#usage
